
DROP TABLE IF EXISTS `stg`.`media_emedia_tmall_wxt_campaign_report`;
CREATE TABLE IF NOT EXISTS `stg`.`media_emedia_tmall_wxt_campaign_report` (
  `store_id` INT,
  `ad_date` STRING,
  `effect` INT,
  `effect_days` INT,
  `effect_type` STRING,
  `campaign_id` BIGINT,
  `campaign_name` STRING,
  `biz_code` STRING,
  `item_id` BIGINT,
  `charge` DOUBLE,
  `click` INT,
  `ad_pv` INT,
  `ctr` DOUBLE,
  `ecpm` DOUBLE,
  `ecpc` DOUBLE,
  `car_num` INT,
  `dir_car_num` INT,
  `indir_car_num` INT,
  `inshop_item_col_num` INT,
  `inshop_item_col_car_num_cost` INT,
  `alipay_inshop_amt` DOUBLE,
  `alipay_inshop_num` INT,
  `cvr` DOUBLE,
  `roi` DOUBLE,
  `prepay_inshop_amt` DOUBLE,
  `prepay_inshop_num` INT,
  `no_lalipay_inshop_amt_proprtion` DOUBLE,
  `dir_alipay_inshop_num` INT,
  `dir_alipay_inshop_amt` DOUBLE,
  `indir_alipay_inshop_num` INT,
  `indir_alipay_inshop_amt` DOUBLE,
  `sample_alipay_num` INT,
  `sample_alipay_amt` DOUBLE,
  `data_source` STRING,
  `dw_batch_id` STRING)
USING delta
LOCATION 'dbfs:/mnt/qa/data_warehouse/media_stg.db/media_emedia_tmall_wxt_campaign_report';



DROP TABLE IF EXISTS `dwd`.`media_emedia_tmall_wxt_campaign_report_success`;
CREATE TABLE IF NOT EXISTS `dwd`.`media_emedia_tmall_wxt_campaign_report_success` (
  `store_id` INT,
  `ad_date` STRING,
  `effect` INT,
  `effect_days` INT,
  `effect_type` STRING,
  `campaign_id` BIGINT,
  `campaign_name` STRING,
  `biz_code` STRING,
  `item_id` BIGINT,
  `charge` DOUBLE,
  `click` INT,
  `ad_pv` INT,
  `ctr` DOUBLE,
  `ecpm` DOUBLE,
  `ecpc` DOUBLE,
  `car_num` INT,
  `dir_car_num` INT,
  `indir_car_num` INT,
  `inshop_item_col_num` INT,
  `inshop_item_col_car_num_cost` INT,
  `alipay_inshop_amt` DOUBLE,
  `alipay_inshop_num` INT,
  `cvr` DOUBLE,
  `roi` DOUBLE,
  `prepay_inshop_amt` DOUBLE,
  `prepay_inshop_num` INT,
  `no_lalipay_inshop_amt_proprtion` DOUBLE,
  `dir_alipay_inshop_num` INT,
  `dir_alipay_inshop_amt` DOUBLE,
  `indir_alipay_inshop_num` INT,
  `indir_alipay_inshop_amt` DOUBLE,
  `sample_alipay_num` INT,
  `sample_alipay_amt` DOUBLE,
  `data_source` STRING,
  `dw_batch_id` STRING,
  `category_id` STRING,
  `brand_id` STRING,
  `etl_date` DATE,
  `etl_create_time` TIMESTAMP)
USING delta
LOCATION 'dbfs:/mnt/qa/data_warehouse/media_dwd.db/media_emedia_tmall_wxt_campaign_report_success';



DROP TABLE IF EXISTS `dwd`.`media_emedia_tmall_wxt_campaign_report_fail`;
CREATE TABLE IF NOT EXISTS `dwd`.`media_emedia_tmall_wxt_campaign_report_fail` (
  `store_id` INT,
  `ad_date` STRING,
  `effect` INT,
  `effect_days` INT,
  `effect_type` STRING,
  `campaign_id` BIGINT,
  `campaign_name` STRING,
  `biz_code` STRING,
  `item_id` BIGINT,
  `charge` DOUBLE,
  `click` INT,
  `ad_pv` INT,
  `ctr` DOUBLE,
  `ecpm` DOUBLE,
  `ecpc` DOUBLE,
  `car_num` INT,
  `dir_car_num` INT,
  `indir_car_num` INT,
  `inshop_item_col_num` INT,
  `inshop_item_col_car_num_cost` INT,
  `alipay_inshop_amt` DOUBLE,
  `alipay_inshop_num` INT,
  `cvr` DOUBLE,
  `roi` DOUBLE,
  `prepay_inshop_amt` DOUBLE,
  `prepay_inshop_num` INT,
  `no_lalipay_inshop_amt_proprtion` DOUBLE,
  `dir_alipay_inshop_num` INT,
  `dir_alipay_inshop_amt` DOUBLE,
  `indir_alipay_inshop_num` INT,
  `indir_alipay_inshop_amt` DOUBLE,
  `sample_alipay_num` INT,
  `sample_alipay_amt` DOUBLE,
  `data_source` STRING,
  `dw_batch_id` STRING,
  `category_id` STRING,
  `brand_id` STRING,
  `etl_date` DATE,
  `etl_create_time` TIMESTAMP)
USING delta
LOCATION 'dbfs:/mnt/qa/data_warehouse/media_dwd.db/media_emedia_tmall_wxt_campaign_report_fail';
