-- jd sem campaign
DROP TABLE IF EXISTS `dws`.`tb_emedia_jd_sem_campaign_mapping_success`;
CREATE TABLE IF NOT EXISTS `dws`.`tb_emedia_jd_sem_campaign_mapping_success` (
    campaignId String ,
    campaignName String ,
    campaignPutType String ,
    campaignType String ,
    clicks String ,
    cost String ,
    couponCnt String ,
    CPA String ,
    CPC String ,
    CPM String ,
    CTR String ,
    date String ,
    deliveryVersion String ,
    depthPassengerCnt String ,
    directCartCnt String ,
    directOrderCnt String ,
    directOrderSum String ,
    goodsAttentionCnt String ,
    impressions String ,
    indirectCartCnt String ,
    indirectOrderCnt String ,
    indirectOrderSum String ,
    mobileType String ,
    newCustomersCnt String ,
    clickDate String ,
    pin String ,
    preorderCnt String ,
    presaleDirectOrderCnt String ,
    presaleDirectOrderSum String ,
    presaleIndirectOrderCnt String ,
    presaleIndirectOrderSum String ,
    putType String ,
    shopAttentionCnt String ,
    totalCartCnt String ,
    totalOrderCnt String ,
    totalOrderCVS String ,
    totalOrderROI String ,
    totalOrderSum String ,
    totalPresaleOrderCnt String ,
    totalPresaleOrderSum String ,
    visitorCnt String ,
    visitPageCnt String ,
    visitTimeAverage String ,
    req_startDay String ,
    req_endDay String ,
    req_productName String ,
    req_page String ,
    req_pageSize String ,
    req_clickOrOrderDay String ,
    req_clickOrOrderCaliber String ,
    req_isDaily String ,
    req_pin String ,
    req_orderStatusCategory String ,
    req_giftFlag String ,
    dw_resource String ,
    dw_create_time String ,
    dw_batch_number String ,
    category_id STRING,
    brand_id STRING,
    `etl_date` DATE,
    `etl_create_time` TIMESTAMP
)
USING delta
PARTITIONED BY (`date`)
LOCATION  'dbfs:/mnt/${spark.dbr_env}/data_warehouse/media_dws.db/tb_emedia_jd_sem_campaign_mapping_success';


DROP TABLE IF EXISTS `stg`.`tb_emedia_jd_sem_campaign_mapping_fail`;
CREATE TABLE IF NOT EXISTS `stg`.`tb_emedia_jd_sem_campaign_mapping_fail` (
  campaignId String ,
    campaignName String ,
    campaignPutType String ,
    campaignType String ,
    clicks String ,
    cost String ,
    couponCnt String ,
    CPA String ,
    CPC String ,
    CPM String ,
    CTR String ,
    date String ,
    deliveryVersion String ,
    depthPassengerCnt String ,
    directCartCnt String ,
    directOrderCnt String ,
    directOrderSum String ,
    goodsAttentionCnt String ,
    impressions String ,
    indirectCartCnt String ,
    indirectOrderCnt String ,
    indirectOrderSum String ,
    mobileType String ,
    newCustomersCnt String ,
    clickDate String ,
    pin String ,
    preorderCnt String ,
    presaleDirectOrderCnt String ,
    presaleDirectOrderSum String ,
    presaleIndirectOrderCnt String ,
    presaleIndirectOrderSum String ,
    putType String ,
    shopAttentionCnt String ,
    totalCartCnt String ,
    totalOrderCnt String ,
    totalOrderCVS String ,
    totalOrderROI String ,
    totalOrderSum String ,
    totalPresaleOrderCnt String ,
    totalPresaleOrderSum String ,
    visitorCnt String ,
    visitPageCnt String ,
    visitTimeAverage String ,
    req_startDay String ,
    req_endDay String ,
    req_productName String ,
    req_page String ,
    req_pageSize String ,
    req_clickOrOrderDay String ,
    req_clickOrOrderCaliber String ,
    req_isDaily String ,
    req_pin String ,
    req_orderStatusCategory String ,
    req_giftFlag String ,
    dw_resource String ,
    dw_create_time String ,
    dw_batch_number String ,
    category_id STRING,
    brand_id STRING,
    `etl_date` DATE,
    `etl_create_time` TIMESTAMP
)
USING delta
PARTITIONED BY (`date`)
LOCATION  'dbfs:/mnt/${spark.dbr_env}/data_warehouse/media_stg.db/tb_emedia_jd_sem_campaign_mapping_fail';


-- auto optimize(2022-04-20)
ALTER TABLE `dws`.`tb_emedia_jd_sem_campaign_mapping_success` SET TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);
ALTER TABLE `stg`.`tb_emedia_jd_sem_campaign_mapping_fail` SET TBLPROPERTIES (delta.autoOptimize.optimizeWrite = true, delta.autoOptimize.autoCompact = true);


