drop table `dws`.`tb_emedia_vip_otd_mapping_success`;
CREATE TABLE `dws`.`tb_emedia_vip_otd_mapping_success` (
  date String ,
  channel String ,
  campaign_id String ,
  campaign_title String ,
  ad_id String ,
  ad_title String ,
  placement_id String ,
  placement_title String ,
  impression String ,
  click String ,
  cost String ,
  click_rate String ,
  cost_per_click String ,
  cost_per_mille String ,
  app_waken_pv String ,
  cost_per_app_waken_uv String ,
  app_waken_uv String ,
  app_waken_rate String ,
  miniapp_uv String ,
  app_uv String ,
  cost_per_app_uv String ,
  cost_per_miniapp_uv String ,
  general_uv String ,
  product_uv String ,
  special_uv String ,
  book_customer_in_24hour String ,
  new_customer_in_24hour String ,
  customer_in_24hour String ,
  book_sales_in_24hour String ,
  sales_in_24hour String ,
  book_orders_in_24hour String ,
  orders_in_24hour String ,
  book_roi_in_24hour String ,
  roi_in_24hour String ,
  book_customer_in_14day String ,
  new_customer_in_14day String ,
  customer_in_14day String ,
  book_sales_in_14day String ,
  sales_in_14day String ,
  book_orders_in_14day String ,
  orders_in_14day String ,
  book_roi_in_14day String ,
  roi_in_14day String ,
  req_advertiser_id String ,
  req_channel String ,
  req_level String ,
  req_start_date String ,
  req_end_date String ,
  dw_batch_number String ,
  dw_create_time String ,
  dw_resource String ,
  effect String ,
  category_id String ,
  brand_id String ,
  `etl_date` DATE,
  `etl_create_time` TIMESTAMP)
USING delta
PARTITIONED BY (date)
LOCATION  'dbfs:/mnt/qa/data_warehouse/media_dws.db/tb_emedia_vip_otd_mapping_success'


%sql

drop table `dws`.`tb_emedia_vip_otd_mapping_fail`;
CREATE TABLE `dws`.`tb_emedia_vip_otd_mapping_fail` (
  date String ,
  channel String ,
  campaign_id String ,
  campaign_title String ,
  ad_id String ,
  ad_title String ,
  placement_id String ,
  placement_title String ,
  impression String ,
  click String ,
  cost String ,
  click_rate String ,
  cost_per_click String ,
  cost_per_mille String ,
  app_waken_pv String ,
  cost_per_app_waken_uv String ,
  app_waken_uv String ,
  app_waken_rate String ,
  miniapp_uv String ,
  app_uv String ,
  cost_per_app_uv String ,
  cost_per_miniapp_uv String ,
  general_uv String ,
  product_uv String ,
  special_uv String ,
  book_customer_in_24hour String ,
  new_customer_in_24hour String ,
  customer_in_24hour String ,
  book_sales_in_24hour String ,
  sales_in_24hour String ,
  book_orders_in_24hour String ,
  orders_in_24hour String ,
  book_roi_in_24hour String ,
  roi_in_24hour String ,
  book_customer_in_14day String ,
  new_customer_in_14day String ,
  customer_in_14day String ,
  book_sales_in_14day String ,
  sales_in_14day String ,
  book_orders_in_14day String ,
  orders_in_14day String ,
  book_roi_in_14day String ,
  roi_in_14day String ,
  req_advertiser_id String ,
  req_channel String ,
  req_level String ,
  req_start_date String ,
  req_end_date String ,
  dw_batch_number String ,
  dw_create_time String ,
  dw_resource String ,
  effect String )
USING delta
LOCATION  'dbfs:/mnt/qa/data_warehouse/media_dws.db/tb_emedia_vip_otd_mapping_fail'
